### ISSUE TITLE
i think event loop in WebSocketFeed->subscribeChannels should return to outside

### ISSUE THREAD

**Issue by qhxin** [Kucoin/kumex-php-sdk#2]
in WebSocketFeed->subscribeChannels function, there's a `$loop = Factory::create();`, and it use `$loop->run();` after `RatchetConnector ` registered.

so, when i want to use EventLoop outside the sdk, i can't get the WebSocketFeed's $loop.

i think $loop should be a public field in WebSocketFeed so i can use it outside and run in my control;

**Comment by hhxsv5** [comment]
Upgrade to [v1.0.13](https://github.com/Kucoin/kumex-php-sdk/releases/tag/v1.0.13).
Thanks for your contribution. @niulingyun
